// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("FE4C7448-2B22-44FD-BE7C-4F8BF2DBF4EF")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("GameTheory.Games.Hangman.Tests")]
[assembly: ComVisible(false)]
