//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTheory.Games.PositivelyPerfectParfaitGame {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameTheory.Games.PositivelyPerfectParfaitGame.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Scoops.
        /// </summary>
        public static string AvailableScoops {
            get {
                return ResourceManager.GetString("AvailableScoops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cherry.
        /// </summary>
        public static string Cherry {
            get {
                return ResourceManager.GetString("Cherry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chocolate.
        /// </summary>
        public static string Flavor_Chocolate {
            get {
                return ResourceManager.GetString("Flavor_Chocolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Vanilla.
        /// </summary>
        public static string Flavor_FrenchVanilla {
            get {
                return ResourceManager.GetString("Flavor_FrenchVanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mint.
        /// </summary>
        public static string Flavor_Mint {
            get {
                return ResourceManager.GetString("Flavor_Mint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strawberry.
        /// </summary>
        public static string Flavor_Strawberry {
            get {
                return ResourceManager.GetString("Flavor_Strawberry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lose a {0} scoop.
        /// </summary>
        public static string LoseAScoop {
            get {
                return ResourceManager.GetString("LoseAScoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positively Perfect Parfait Game.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play out.
        /// </summary>
        public static string PlayOut {
            get {
                return ResourceManager.GetString("PlayOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play the game until everyone has completed their parfait?.
        /// </summary>
        public static string PlayOutDescription {
            get {
                return ResourceManager.GetString("PlayOutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch your {0} for a {1} from {2}.
        /// </summary>
        public static string SwitchAScoop {
            get {
                return ResourceManager.GetString("SwitchAScoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a cherry.
        /// </summary>
        public static string TakeACherry {
            get {
                return ResourceManager.GetString("TakeACherry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a {0} scoop.
        /// </summary>
        public static string TakeAScoop {
            get {
                return ResourceManager.GetString("TakeAScoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twirl the spinner.
        /// </summary>
        public static string TwirlTheSpinner {
            get {
                return ResourceManager.GetString("TwirlTheSpinner", resourceCulture);
            }
        }
    }
}
