// <auto-generated />
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProduct("GameTheory")]
[assembly: AssemblyCopyright("Copyright © 2014 John Gietzen")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: ComVisible(false)]
