//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTheory.Games.Lotus {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameTheory.Games.Lotus.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim a scoring token.
        /// </summary>
        public static string ClaimScoringToken {
            get {
                return ResourceManager.GetString("ClaimScoringToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim the {0} power.
        /// </summary>
        public static string ClaimSpecialPowerFormat {
            get {
                return ResourceManager.GetString("ClaimSpecialPowerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw a card.
        /// </summary>
        public static string DrawCard {
            get {
                return ResourceManager.GetString("DrawCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange {0}.
        /// </summary>
        public static string ExchangePetalCardsFormat {
            get {
                return ResourceManager.GetString("ExchangePetalCardsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cherry Blossom.
        /// </summary>
        public static string FlowerType_CherryBlossom {
            get {
                return ResourceManager.GetString("FlowerType_CherryBlossom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iris.
        /// </summary>
        public static string FlowerType_Iris {
            get {
                return ResourceManager.GetString("FlowerType_Iris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lily.
        /// </summary>
        public static string FlowerType_Lily {
            get {
                return ResourceManager.GetString("FlowerType_Lily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lotus.
        /// </summary>
        public static string FlowerType_Lotus {
            get {
                return ResourceManager.GetString("FlowerType_Lotus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primrose.
        /// </summary>
        public static string FlowerType_Primrose {
            get {
                return ResourceManager.GetString("FlowerType_Primrose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0}.
        /// </summary>
        public static string GuardianBonusFormat {
            get {
                return ResourceManager.GetString("GuardianBonusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand.
        /// </summary>
        public static string Hand {
            get {
                return ResourceManager.GetString("Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move a guardian to the {0}.
        /// </summary>
        public static string MoveGuardianFormat {
            get {
                return ResourceManager.GetString("MoveGuardianFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lotus.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string PetalCardFormat {
            get {
                return ResourceManager.GetString("PetalCardFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play {0}.
        /// </summary>
        public static string PlayPetalCardsFormat {
            get {
                return ResourceManager.GetString("PlayPetalCardsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoring Pile.
        /// </summary>
        public static string ScoringPile {
            get {
                return ResourceManager.GetString("ScoringPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoring Tokens.
        /// </summary>
        public static string ScoringTokens {
            get {
                return ResourceManager.GetString("ScoringTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Powers.
        /// </summary>
        public static string SpecialPowers {
            get {
                return ResourceManager.GetString("SpecialPowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elder Guardian.
        /// </summary>
        public static string SpecialPowers_ElderGuardian {
            get {
                return ResourceManager.GetString("SpecialPowers_ElderGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlightened Path.
        /// </summary>
        public static string SpecialPowers_EnlightenedPath {
            get {
                return ResourceManager.GetString("SpecialPowers_EnlightenedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite Growth.
        /// </summary>
        public static string SpecialPowers_InfiniteGrowth {
            get {
                return ResourceManager.GetString("SpecialPowers_InfiniteGrowth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string SpecialPowers_None {
            get {
                return ResourceManager.GetString("SpecialPowers_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (taken).
        /// </summary>
        public static string Taken {
            get {
                return ResourceManager.GetString("Taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take {0}.
        /// </summary>
        public static string TakeWildflowerFormat {
            get {
                return ResourceManager.GetString("TakeWildflowerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildflowers.
        /// </summary>
        public static string Wildflowers {
            get {
                return ResourceManager.GetString("Wildflowers", resourceCulture);
            }
        }
    }
}
