// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("D1EAF83B-EAFD-499F-BF08-84B7B6B0E895")]
[assembly: CLSCompliant(true)]
[assembly: ComVisible(false)]
