// <auto-generated />
using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("GameTheory")]
[assembly: AssemblyDescription("")]
[assembly: NeutralResourcesLanguage("en-US")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("GameTheory.Tests")]
