// <auto-generated />
using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("GameTheory")]
[assembly: AssemblyDescription("")]
[assembly: Guid("917f5eae-59a7-4b83-a485-b060e3754b1f")]
[assembly: NeutralResourcesLanguage("en-US")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("GameTheory.Tests")]
