// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("EA1C566E-C4E1-4879-B516-B9D94A718245")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("GameTheory.Tests")]
[assembly: ComVisible(false)]
