//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTheory.Games.Splendor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameTheory.Games.Splendor.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Tokens.
        /// </summary>
        public static string AvailableTokens {
            get {
                return ResourceManager.GetString("AvailableTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invide {0} to visit.
        /// </summary>
        public static string ChooseNoble {
            get {
                return ResourceManager.GetString("ChooseNoble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} +{1}.
        /// </summary>
        public static string DevelopmentCard {
            get {
                return ResourceManager.GetString("DevelopmentCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Cards.
        /// </summary>
        public static string DevelopmentCards {
            get {
                return ResourceManager.GetString("DevelopmentCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard {0}.
        /// </summary>
        public static string DiscardTokens {
            get {
                return ResourceManager.GetString("DiscardTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand.
        /// </summary>
        public static string Hand {
            get {
                return ResourceManager.GetString("Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splendor.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noble +{0} {1}.
        /// </summary>
        public static string Noble {
            get {
                return ResourceManager.GetString("Noble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobles.
        /// </summary>
        public static string Nobles {
            get {
                return ResourceManager.GetString("Nobles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prestige.
        /// </summary>
        public static string Prestige {
            get {
                return ResourceManager.GetString("Prestige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase {0} for free.
        /// </summary>
        public static string PurchaseCardForFree {
            get {
                return ResourceManager.GetString("PurchaseCardForFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase {0} for {1}.
        /// </summary>
        public static string PurchaseCardForTokens {
            get {
                return ResourceManager.GetString("PurchaseCardForTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remaining.
        /// </summary>
        public static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve {0} (cost: {1}).
        /// </summary>
        public static string ReserveCard {
            get {
                return ResourceManager.GetString("ReserveCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve {0} (cost: {1}) and take {2}.
        /// </summary>
        public static string ReserveCardAndTakeJoker {
            get {
                return ResourceManager.GetString("ReserveCardAndTakeJoker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve from deck {0}.
        /// </summary>
        public static string ReserveFromDeck {
            get {
                return ResourceManager.GetString("ReserveFromDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve from deck {0} and take {1}.
        /// </summary>
        public static string ReserveFromDeckAndTakeJoker {
            get {
                return ResourceManager.GetString("ReserveFromDeckAndTakeJoker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take {0}.
        /// </summary>
        public static string TakeTokens {
            get {
                return ResourceManager.GetString("TakeTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond.
        /// </summary>
        public static string Token_Diamond {
            get {
                return ResourceManager.GetString("Token_Diamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emerald.
        /// </summary>
        public static string Token_Emerald {
            get {
                return ResourceManager.GetString("Token_Emerald", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Joker.
        /// </summary>
        public static string Token_GoldJoker {
            get {
                return ResourceManager.GetString("Token_GoldJoker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onyx.
        /// </summary>
        public static string Token_Onyx {
            get {
                return ResourceManager.GetString("Token_Onyx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruby.
        /// </summary>
        public static string Token_Ruby {
            get {
                return ResourceManager.GetString("Token_Ruby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sapphire.
        /// </summary>
        public static string Token_Sapphire {
            get {
                return ResourceManager.GetString("Token_Sapphire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens.
        /// </summary>
        public static string Tokens {
            get {
                return ResourceManager.GetString("Tokens", resourceCulture);
            }
        }
    }
}
