//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTheory.Gdl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameTheory.Gdl.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expressions of type &apos;{0}&apos; are unsupported..
        /// </summary>
        internal static string GDL001_ERROR_UnsupportedExpressionType {
            get {
                return ResourceManager.GetString("GDL001_ERROR_UnsupportedExpressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant &apos;{0}&apos; is defined as a &apos;{1}&apos; but used as a &apos;{2}&apos;..
        /// </summary>
        internal static string GDL002_ERROR_InconsistentConstantSemantics {
            get {
                return ResourceManager.GetString("GDL002_ERROR_InconsistentConstantSemantics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant &apos;{0}&apos; is defined with arity &apos;{1}&apos; but used as with arity &apos;{2}&apos;..
        /// </summary>
        internal static string GDL003_ERROR_InconsistentArity {
            get {
                return ResourceManager.GetString("GDL003_ERROR_InconsistentArity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence variables are not supported..
        /// </summary>
        internal static string GDL004_ERROR_SequenceVariablesUnsupported {
            get {
                return ResourceManager.GetString("GDL004_ERROR_SequenceVariablesUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The head of a rule must be an atomic sentence..
        /// </summary>
        internal static string GDL005_ERROR_RuleHeadMustBeAtomic {
            get {
                return ResourceManager.GetString("GDL005_ERROR_RuleHeadMustBeAtomic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rule body must only contain atomic sentences or negations of atomic sentences..
        /// </summary>
        internal static string GDL006_ERROR_RuleBodyMustBeAtomic {
            get {
                return ResourceManager.GetString("GDL006_ERROR_RuleBodyMustBeAtomic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error was encountered while generating the game code. {0}.
        /// </summary>
        internal static string GDL101_ERROR_ErrorGeneratingCode {
            get {
                return ResourceManager.GetString("GDL101_ERROR_ErrorGeneratingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error was encountered whle compiling the generated type. {0}.
        /// </summary>
        internal static string GDL102_ERROR_ErrorComilingType {
            get {
                return ResourceManager.GetString("GDL102_ERROR_ErrorComilingType", resourceCulture);
            }
        }
    }
}
