//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTheory.Games.Ergo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameTheory.Games.Ergo.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal.
        /// </summary>
        public static string Deal {
            get {
                return ResourceManager.GetString("Deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard {0}.
        /// </summary>
        public static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw cards.
        /// </summary>
        public static string DrawCards {
            get {
                return ResourceManager.GetString("DrawCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergo.
        /// </summary>
        public static string Ergo {
            get {
                return ResourceManager.GetString("Ergo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallacy.
        /// </summary>
        public static string Fallacy {
            get {
                return ResourceManager.GetString("Fallacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand.
        /// </summary>
        public static string Hand {
            get {
                return ResourceManager.GetString("Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justification.
        /// </summary>
        public static string Justification {
            get {
                return ResourceManager.GetString("Justification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {0} to {1}:{2} and {3} to {4}:{5} using {6}.
        /// </summary>
        public static string MoveSymbolsWithRevolution {
            get {
                return ResourceManager.GetString("MoveSymbolsWithRevolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergo.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place {0} at {1}:{2}.
        /// </summary>
        public static string PlaceCard {
            get {
                return ResourceManager.GetString("PlaceCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place {0} as {1} at {2}:{3}.
        /// </summary>
        public static string PlaceCardAs {
            get {
                return ResourceManager.GetString("PlaceCardAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play {0}.
        /// </summary>
        public static string PlayCard {
            get {
                return ResourceManager.GetString("PlayCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play {0} as {1}.
        /// </summary>
        public static string PlayCardAs {
            get {
                return ResourceManager.GetString("PlayCardAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play {0} on {1}.
        /// </summary>
        public static string PlayFallacy {
            get {
                return ResourceManager.GetString("PlayFallacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof.
        /// </summary>
        public static string Proof {
            get {
                return ResourceManager.GetString("Proof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove fallacy with {0}.
        /// </summary>
        public static string RemoveFallacy {
            get {
                return ResourceManager.GetString("RemoveFallacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove at {0}:{1} using {2}.
        /// </summary>
        public static string RemoveSymbolWithTabulaRasa {
            get {
                return ResourceManager.GetString("RemoveSymbolWithTabulaRasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolution.
        /// </summary>
        public static string Revolution {
            get {
                return ResourceManager.GetString("Revolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores.
        /// </summary>
        public static string Scores {
            get {
                return ResourceManager.GetString("Scores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;.
        /// </summary>
        public static string Symbol_And {
            get {
                return ResourceManager.GetString("Symbol_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string Symbol_BlayerD {
            get {
                return ResourceManager.GetString("Symbol_BlayerD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        public static string Symbol_LeftParenthesis {
            get {
                return ResourceManager.GetString("Symbol_LeftParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~.
        /// </summary>
        public static string Symbol_Not {
            get {
                return ResourceManager.GetString("Symbol_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.
        /// </summary>
        public static string Symbol_Or {
            get {
                return ResourceManager.GetString("Symbol_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string Symbol_PlayerA {
            get {
                return ResourceManager.GetString("Symbol_PlayerA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string Symbol_PlayerB {
            get {
                return ResourceManager.GetString("Symbol_PlayerB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string Symbol_PlayerC {
            get {
                return ResourceManager.GetString("Symbol_PlayerC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string Symbol_PlayerD {
            get {
                return ResourceManager.GetString("Symbol_PlayerD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        public static string Symbol_RightParenthesis {
            get {
                return ResourceManager.GetString("Symbol_RightParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =&gt;.
        /// </summary>
        public static string Symbol_Then {
            get {
                return ResourceManager.GetString("Symbol_Then", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        public static string Symbols {
            get {
                return ResourceManager.GetString("Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabula Rasa.
        /// </summary>
        public static string TabulaRasa {
            get {
                return ResourceManager.GetString("TabulaRasa", resourceCulture);
            }
        }
    }
}
