//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTheory.Games.CenturySpiceRoad {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameTheory.Games.CenturySpiceRoad.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquire {0}.
        /// </summary>
        public static string AcquireMerchantCard {
            get {
                return ResourceManager.GetString("AcquireMerchantCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquire {0} and gain {1}.
        /// </summary>
        public static string AcquireMerchantCardAndBonus {
            get {
                return ResourceManager.GetString("AcquireMerchantCardAndBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Tokens.
        /// </summary>
        public static string AvailableTokens {
            get {
                return ResourceManager.GetString("AvailableTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bonus.
        /// </summary>
        public static string Bonus {
            get {
                return ResourceManager.GetString("Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caravan.
        /// </summary>
        public static string Caravan {
            get {
                return ResourceManager.GetString("Caravan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim {0}.
        /// </summary>
        public static string ClaimPointCard {
            get {
                return ResourceManager.GetString("ClaimPointCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard {0}.
        /// </summary>
        public static string DiscardSpices {
            get {
                return ResourceManager.GetString("DiscardSpices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain {0}.
        /// </summary>
        public static string GainSpices {
            get {
                return ResourceManager.GetString("GainSpices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand.
        /// </summary>
        public static string Hand {
            get {
                return ResourceManager.GetString("Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Cards.
        /// </summary>
        public static string MerchantCards {
            get {
                return ResourceManager.GetString("MerchantCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Century Spice Road.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay {0}.
        /// </summary>
        public static string PaySpices {
            get {
                return ResourceManager.GetString("PaySpices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play {0}.
        /// </summary>
        public static string PlayCard {
            get {
                return ResourceManager.GetString("PlayCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0}.
        /// </summary>
        public static string PointCard {
            get {
                return ResourceManager.GetString("PointCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Cards.
        /// </summary>
        public static string PointCards {
            get {
                return ResourceManager.GetString("PointCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest.
        /// </summary>
        public static string Rest {
            get {
                return ResourceManager.GetString("Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardamom.
        /// </summary>
        public static string Spice_Cardamom {
            get {
                return ResourceManager.GetString("Spice_Cardamom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinnamon.
        /// </summary>
        public static string Spice_Cinnamon {
            get {
                return ResourceManager.GetString("Spice_Cinnamon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saffron.
        /// </summary>
        public static string Spice_Saffron {
            get {
                return ResourceManager.GetString("Spice_Saffron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turmeric.
        /// </summary>
        public static string Spice_Turmeric {
            get {
                return ResourceManager.GetString("Spice_Turmeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade {0} for {1}.
        /// </summary>
        public static string TradeCard {
            get {
                return ResourceManager.GetString("TradeCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade ({0}).
        /// </summary>
        public static string UpgradeCard {
            get {
                return ResourceManager.GetString("UpgradeCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade {0} to {1}.
        /// </summary>
        public static string UpgradeSpice {
            get {
                return ResourceManager.GetString("UpgradeSpice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yield upgrade.
        /// </summary>
        public static string YieldUpgrade {
            get {
                return ResourceManager.GetString("YieldUpgrade", resourceCulture);
            }
        }
    }
}
