// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("2B1FFEBA-4D0B-46F8-826D-3CBE09DDDE82")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("GameTheory.Tests")]
[assembly: ComVisible(false)]
