//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTheory.Games.SevenDragons {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameTheory.Games.SevenDragons.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose {0} at {1}.
        /// </summary>
        public static string ChooseCard {
            get {
                return ResourceManager.GetString("ChooseCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Color_Black {
            get {
                return ResourceManager.GetString("Color_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Color_Blue {
            get {
                return ResourceManager.GetString("Color_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string Color_Gold {
            get {
                return ResourceManager.GetString("Color_Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Color_Green {
            get {
                return ResourceManager.GetString("Color_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow.
        /// </summary>
        public static string Color_Rainbow {
            get {
                return ResourceManager.GetString("Color_Rainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Color_Red {
            get {
                return ResourceManager.GetString("Color_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        public static string Color_Silver {
            get {
                return ResourceManager.GetString("Color_Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard {0}.
        /// </summary>
        public static string DiscardActionCard {
            get {
                return ResourceManager.GetString("DiscardActionCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard {0} on bottom.
        /// </summary>
        public static string DiscardActionCardOnBottom {
            get {
                return ResourceManager.GetString("DiscardActionCardOnBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard {0} on top.
        /// </summary>
        public static string DiscardActionCardOnTop {
            get {
                return ResourceManager.GetString("DiscardActionCardOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw a card.
        /// </summary>
        public static string DrawCard {
            get {
                return ResourceManager.GetString("DrawCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw {0} cards.
        /// </summary>
        public static string DrawCards {
            get {
                return ResourceManager.GetString("DrawCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        public static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand.
        /// </summary>
        public static string Hand {
            get {
                return ResourceManager.GetString("Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include actions.
        /// </summary>
        public static string IncludeActions {
            get {
                return ResourceManager.GetString("IncludeActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include action cards in the deck?.
        /// </summary>
        public static string IncludeActionsDescription {
            get {
                return ResourceManager.GetString("IncludeActionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move a card.
        /// </summary>
        public static string MoveACard {
            get {
                return ResourceManager.GetString("MoveACard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {0} from {1} to {2}.
        /// </summary>
        public static string MoveCard {
            get {
                return ResourceManager.GetString("MoveCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Dragons.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play {0}.
        /// </summary>
        public static string PlayActionCard {
            get {
                return ResourceManager.GetString("PlayActionCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play {0} at {1}.
        /// </summary>
        public static string PlayDragonCard {
            get {
                return ResourceManager.GetString("PlayDragonCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate goals along turn order.
        /// </summary>
        public static string RotateAlongTurnOrder {
            get {
                return ResourceManager.GetString("RotateAlongTurnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate goals.
        /// </summary>
        public static string RotateGoals {
            get {
                return ResourceManager.GetString("RotateGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate goals opposite turn order.
        /// </summary>
        public static string RotateOppositeTurnOrder {
            get {
                return ResourceManager.GetString("RotateOppositeTurnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade goals.
        /// </summary>
        public static string TradeGoals {
            get {
                return ResourceManager.GetString("TradeGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade goals with position {0}.
        /// </summary>
        public static string TradeGoalsWithPosition {
            get {
                return ResourceManager.GetString("TradeGoalsWithPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade goals with position {0} ({1}).
        /// </summary>
        public static string TradeGoalsWithPositionAndPlayer {
            get {
                return ResourceManager.GetString("TradeGoalsWithPositionAndPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade hands.
        /// </summary>
        public static string TradeHands {
            get {
                return ResourceManager.GetString("TradeHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade hands with {0}.
        /// </summary>
        public static string TradeHandsWithPlayer {
            get {
                return ResourceManager.GetString("TradeHandsWithPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zap a card.
        /// </summary>
        public static string ZapACard {
            get {
                return ResourceManager.GetString("ZapACard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zap {0} at {1}.
        /// </summary>
        public static string ZapCard {
            get {
                return ResourceManager.GetString("ZapCard", resourceCulture);
            }
        }
    }
}
