//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTheory.Games.Skull {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameTheory.Games.Skull.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a {0}.
        /// </summary>
        public static string AddACard {
            get {
                return ResourceManager.GetString("AddACard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid {0}.
        /// </summary>
        public static string Bid {
            get {
                return ResourceManager.GetString("Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flower.
        /// </summary>
        public static string Card_Flower {
            get {
                return ResourceManager.GetString("Card_Flower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skull.
        /// </summary>
        public static string Card_Skull {
            get {
                return ResourceManager.GetString("Card_Skull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ????.
        /// </summary>
        public static string Card_Unknown {
            get {
                return ResourceManager.GetString("Card_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose {0} to start next.
        /// </summary>
        public static string ChooseStartingPlayer {
            get {
                return ResourceManager.GetString("ChooseStartingPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard {0}.
        /// </summary>
        public static string DiscardCard {
            get {
                return ResourceManager.GetString("DiscardCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand.
        /// </summary>
        public static string Hand {
            get {
                return ResourceManager.GetString("Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skull.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present cards as {0}.
        /// </summary>
        public static string PresentCards {
            get {
                return ResourceManager.GetString("PresentCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Card #{0}.
        /// </summary>
        public static string RemoveCard {
            get {
                return ResourceManager.GetString("RemoveCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reveall all of your cards.
        /// </summary>
        public static string RevealAllCards {
            get {
                return ResourceManager.GetString("RevealAllCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reveal a card from {0}.
        /// </summary>
        public static string RevealPlayerCard {
            get {
                return ResourceManager.GetString("RevealPlayerCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack.
        /// </summary>
        public static string Stack {
            get {
                return ResourceManager.GetString("Stack", resourceCulture);
            }
        }
    }
}
