//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTheory.Games.LoveLetter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameTheory.Games.LoveLetter.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose {0}.
        /// </summary>
        public static string ChooseTarget {
            get {
                return ResourceManager.GetString("ChooseTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare hands with {0}.
        /// </summary>
        public static string CompareHands {
            get {
                return ResourceManager.GetString("CompareHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard {0}.
        /// </summary>
        public static string DiscardCard {
            get {
                return ResourceManager.GetString("DiscardCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard {0}&apos;s hand.
        /// </summary>
        public static string DiscardHand {
            get {
                return ResourceManager.GetString("DiscardHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard your hand.
        /// </summary>
        public static string DiscardOwnHand {
            get {
                return ResourceManager.GetString("DiscardOwnHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw a card.
        /// </summary>
        public static string DrawCard {
            get {
                return ResourceManager.GetString("DrawCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look at {0}&apos;s hand.
        /// </summary>
        public static string LookAtHand {
            get {
                return ResourceManager.GetString("LookAtHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love Letter.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reveal your hand.
        /// </summary>
        public static string RevealHand {
            get {
                return ResourceManager.GetString("RevealHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade hands with {0}.
        /// </summary>
        public static string TradeHands {
            get {
                return ResourceManager.GetString("TradeHands", resourceCulture);
            }
        }
    }
}
