//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTheory.Gdl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameTheory.Gdl.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expressions of type &apos;{0}&apos; are unsupported..
        /// </summary>
        internal static string GDL001_ERROR_UnsupportedExpressionType {
            get {
                return ResourceManager.GetString("GDL001_ERROR_UnsupportedExpressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant &apos;{0}&apos; with arity &apos;{1}&apos; is used inconsistently.  Used her as &apos;{2}&apos;..
        /// </summary>
        internal static string GDL002_ERROR_InconsistentConstantSemantics {
            get {
                return ResourceManager.GetString("GDL002_ERROR_InconsistentConstantSemantics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The head of a rule must be an atomic sentence..
        /// </summary>
        internal static string GDL005_ERROR_RuleHeadMustBeAtomic {
            get {
                return ResourceManager.GetString("GDL005_ERROR_RuleHeadMustBeAtomic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rule body must only contain atomic sentences or negations of atomic sentences..
        /// </summary>
        internal static string GDL006_ERROR_RuleBodyMustBeAtomic {
            get {
                return ResourceManager.GetString("GDL006_ERROR_RuleBodyMustBeAtomic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relation &apos;{0}&apos; was found in a cycle with &apos;{1}&apos; and the recursion may grow unbounded.  All of the terms in the &apos;{0}&apos; relation must be ground, used directly in the &apos;{1}&apos; relation, or used directly in one other relation in the rule..
        /// </summary>
        internal static string GDL007_ERROR_RecursionResriction {
            get {
                return ResourceManager.GetString("GDL007_ERROR_RecursionResriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;role&apos; relation may only appear in ground atomic sentences..
        /// </summary>
        internal static string GDL008_ERROR_RoleRelationUsedInRule {
            get {
                return ResourceManager.GetString("GDL008_ERROR_RoleRelationUsedInRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;init&apos; relation may not appear in rule bodies..
        /// </summary>
        internal static string GDL009_ERROR_InitRelationUsedInRuleBody {
            get {
                return ResourceManager.GetString("GDL009_ERROR_InitRelationUsedInRuleBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;init&apos; relation may not be used with other game relations..
        /// </summary>
        internal static string GDL010_ERROR_InitRelationDependency {
            get {
                return ResourceManager.GetString("GDL010_ERROR_InitRelationDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;true&apos; relation may only appear in rule bodies..
        /// </summary>
        internal static string GDL011_ERROR_TrueRelationUsedOutsideRuleBody {
            get {
                return ResourceManager.GetString("GDL011_ERROR_TrueRelationUsedOutsideRuleBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;next&apos; relation may only appear as a rule head..
        /// </summary>
        internal static string GDL012_ERROR_NextRelationUsedOutsideRuleHead {
            get {
                return ResourceManager.GetString("GDL012_ERROR_NextRelationUsedOutsideRuleHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;does&apos; relation may only appear in rule bodies..
        /// </summary>
        internal static string GDL013_ERROR_DoesUsedOutsideRuleBody {
            get {
                return ResourceManager.GetString("GDL013_ERROR_DoesUsedOutsideRuleBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;does&apos; relation may not be used with the legal, goal, or terminal relations..
        /// </summary>
        internal static string GDL014_ERROR_DoesRelationDependency {
            get {
                return ResourceManager.GetString("GDL014_ERROR_DoesRelationDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error was encountered while assigning types. {0}.
        /// </summary>
        internal static string GDL099_ERROR_ErrorAssigningTypes {
            get {
                return ResourceManager.GetString("GDL099_ERROR_ErrorAssigningTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error was encountered while assigning names. {0}.
        /// </summary>
        internal static string GDL100_ERROR_ErrorAssigningNames {
            get {
                return ResourceManager.GetString("GDL100_ERROR_ErrorAssigningNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error was encountered whle generating the game code DOM. {0}.
        /// </summary>
        internal static string GDL101_ERROR_ErrorConvertingToCodeDom {
            get {
                return ResourceManager.GetString("GDL101_ERROR_ErrorConvertingToCodeDom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error was encountered while generating the game code. {0}.
        /// </summary>
        internal static string GDL102_ERROR_ErrorGeneratingCode {
            get {
                return ResourceManager.GetString("GDL102_ERROR_ErrorGeneratingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error was encountered whle compiling the generated type. {0}.
        /// </summary>
        internal static string GDL103_ERROR_ErrorComilingType {
            get {
                return ResourceManager.GetString("GDL103_ERROR_ErrorComilingType", resourceCulture);
            }
        }
    }
}
