//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTheory.Games.FiveTribes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameTheory.Games.FiveTribes.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw {0} meeples and place them at {1}.
        /// </summary>
        public static string AddMeeples {
            get {
                return ResourceManager.GetString("AddMeeples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al-Amin.
        /// </summary>
        public static string AlAmin {
            get {
                return ResourceManager.GetString("AlAmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anun-Nak.
        /// </summary>
        public static string AnunNak {
            get {
                return ResourceManager.GetString("AnunNak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assassinate {0} at {1}.
        /// </summary>
        public static string Assasinate {
            get {
                return ResourceManager.GetString("Assasinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assassinate {0} in front of {1}.
        /// </summary>
        public static string AssassinatePlayer {
            get {
                return ResourceManager.GetString("AssassinatePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ba&apos;al.
        /// </summary>
        public static string Baal {
            get {
                return ResourceManager.GetString("Baal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid {0} GC.
        /// </summary>
        public static string Bid {
            get {
                return ResourceManager.GetString("Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid Order Track.
        /// </summary>
        public static string BidOrderTrack {
            get {
                return ResourceManager.GetString("BidOrderTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boaz.
        /// </summary>
        public static string Boaz {
            get {
                return ResourceManager.GetString("Boaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouraq.
        /// </summary>
        public static string Bouraq {
            get {
                return ResourceManager.GetString("Bouraq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhenim.
        /// </summary>
        public static string Dhenim {
            get {
                return ResourceManager.GetString("Dhenim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} +{1}.
        /// </summary>
        public static string Djinn {
            get {
                return ResourceManager.GetString("Djinn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Djinns.
        /// </summary>
        public static string Djinns {
            get {
                return ResourceManager.GetString("Djinns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double the number of meeples your Assassins kill this turn.
        /// </summary>
        public static string DoubleAssassinationCount {
            get {
                return ResourceManager.GetString("DoubleAssassinationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double the amout of GCs your Builders get this turn.
        /// </summary>
        public static string DoubleBuilderGC {
            get {
                return ResourceManager.GetString("DoubleBuilderGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw {0} djinns.
        /// </summary>
        public static string DrawDjinns {
            get {
                return ResourceManager.GetString("DrawDjinns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw the top card from the resource pile.
        /// </summary>
        public static string DrawTopResource {
            get {
                return ResourceManager.GetString("DrawTopResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop {0} at {1}.
        /// </summary>
        public static string DropMeeple {
            get {
                return ResourceManager.GetString("DropMeeple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echidna.
        /// </summary>
        public static string Echidna {
            get {
                return ResourceManager.GetString("Echidna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End turn.
        /// </summary>
        public static string EndTurn {
            get {
                return ResourceManager.GetString("EndTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enki.
        /// </summary>
        public static string Enki {
            get {
                return ResourceManager.GetString("Enki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hagis.
        /// </summary>
        public static string Hagis {
            get {
                return ResourceManager.GetString("Hagis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haurvatat.
        /// </summary>
        public static string Haurvatat {
            get {
                return ResourceManager.GetString("Haurvatat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ibus.
        /// </summary>
        public static string Ibus {
            get {
                return ResourceManager.GetString("Ibus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Dhenim.
        /// </summary>
        public static string IncludeDhenim {
            get {
                return ResourceManager.GetString("IncludeDhenim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the Dhenim djinn?.
        /// </summary>
        public static string IncludeDhenimDescription {
            get {
                return ResourceManager.GetString("IncludeDhenimDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jafaar.
        /// </summary>
        public static string Jafaar {
            get {
                return ResourceManager.GetString("Jafaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kandicha.
        /// </summary>
        public static string Kandicha {
            get {
                return ResourceManager.GetString("Kandicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kumarbi.
        /// </summary>
        public static string Kumarbi {
            get {
                return ResourceManager.GetString("Kumarbi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamia.
        /// </summary>
        public static string Lamia {
            get {
                return ResourceManager.GetString("Lamia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leta.
        /// </summary>
        public static string Leta {
            get {
                return ResourceManager.GetString("Leta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marid.
        /// </summary>
        public static string Marid {
            get {
                return ResourceManager.GetString("Marid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assassin.
        /// </summary>
        public static string Meeple_Assassin {
            get {
                return ResourceManager.GetString("Meeple_Assassin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builder.
        /// </summary>
        public static string Meeple_Builder {
            get {
                return ResourceManager.GetString("Meeple_Builder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elder.
        /// </summary>
        public static string Meeple_Elder {
            get {
                return ResourceManager.GetString("Meeple_Elder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant.
        /// </summary>
        public static string Meeple_Merchant {
            get {
                return ResourceManager.GetString("Meeple_Merchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vizier.
        /// </summary>
        public static string Meeple_Vizier {
            get {
                return ResourceManager.GetString("Meeple_Vizier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monkir.
        /// </summary>
        public static string Monkir {
            get {
                return ResourceManager.GetString("Monkir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move turn marker.
        /// </summary>
        public static string MoveTurnMarker {
            get {
                return ResourceManager.GetString("MoveTurnMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five Tribes.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nekir.
        /// </summary>
        public static string Nekir {
            get {
                return ResourceManager.GetString("Nekir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palace.
        /// </summary>
        public static string Palace {
            get {
                return ResourceManager.GetString("Palace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palm Tree.
        /// </summary>
        public static string PalmTree {
            get {
                return ResourceManager.GetString("PalmTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay {0}.
        /// </summary>
        public static string PayCost {
            get {
                return ResourceManager.GetString("PayCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay {0} GC.
        /// </summary>
        public static string PayGold {
            get {
                return ResourceManager.GetString("PayGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up meeples at {0}.
        /// </summary>
        public static string PickUpMeeples {
            get {
                return ResourceManager.GetString("PickUpMeeples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up all {0} at {1}.
        /// </summary>
        public static string PickUpTribe {
            get {
                return ResourceManager.GetString("PickUpTribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place a Camel at {0}.
        /// </summary>
        public static string PlaceCamel {
            get {
                return ResourceManager.GetString("PlaceCamel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place a Palace at {0}.
        /// </summary>
        public static string PlacePalace {
            get {
                return ResourceManager.GetString("PlacePalace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place a Palm Tree at {0}.
        /// </summary>
        public static string PlacePalmTree {
            get {
                return ResourceManager.GetString("PlacePalmTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remaining.
        /// </summary>
        public static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string ResourcesTrack {
            get {
                return ResourceManager.GetString("ResourcesTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score {0}.
        /// </summary>
        public static string ScoreBuilders {
            get {
                return ResourceManager.GetString("ScoreBuilders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade {0} for {1} GC.
        /// </summary>
        public static string SellMerchandise {
            get {
                return ResourceManager.GetString("SellMerchandise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade {0} for {1}.
        /// </summary>
        public static string SellSlaves {
            get {
                return ResourceManager.GetString("SellSlaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shamhat.
        /// </summary>
        public static string Shamhat {
            get {
                return ResourceManager.GetString("Shamhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sibittis.
        /// </summary>
        public static string Sibittis {
            get {
                return ResourceManager.GetString("Sibittis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip move.
        /// </summary>
        public static string SkipMove {
            get {
                return ResourceManager.GetString("SkipMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip remaining resources.
        /// </summary>
        public static string SkipRemainingResources {
            get {
                return ResourceManager.GetString("SkipRemainingResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip tile sction.
        /// </summary>
        public static string SkipTileAction {
            get {
                return ResourceManager.GetString("SkipTileAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip tribes action.
        /// </summary>
        public static string SkipTribesAction {
            get {
                return ResourceManager.GetString("SkipTribesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sloar.
        /// </summary>
        public static string Sloar {
            get {
                return ResourceManager.GetString("Sloar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sultanate.
        /// </summary>
        public static string Sultanate {
            get {
                return ResourceManager.GetString("Sultanate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take {0} resources.
        /// </summary>
        public static string TakeFirstResources {
            get {
                return ResourceManager.GetString("TakeFirstResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take {0}.
        /// </summary>
        public static string TakeItem {
            get {
                return ResourceManager.GetString("TakeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Order Track.
        /// </summary>
        public static string TurnOrderTrack {
            get {
                return ResourceManager.GetString("TurnOrderTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utug.
        /// </summary>
        public static string Utug {
            get {
                return ResourceManager.GetString("Utug", resourceCulture);
            }
        }
    }
}
