// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("9F5BD348-EB58-4AD4-8ECC-2419AD1C2A71")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("GameTheory.Tests")]
[assembly: ComVisible(false)]
