// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("4BBAB445-3EB3-492B-9467-996FA93DA2BD")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("GameTheory.Tests")]
[assembly: ComVisible(false)]
