// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("91DD19BB-FD29-4DBF-B3A9-9D3E082547FF")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("GameTheory.Tests")]
[assembly: ComVisible(false)]
