// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("3A823A15-EFBD-4EDF-AE50-1D988589644C")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("GameTheory.Games.Chess.Tests")]
[assembly: ComVisible(false)]
